import { IssueCategory, Severity } from '../types';

/**
 * Stable rule definitions. Every finding emitted by the scanner references a `ruleId`
 * defined here. The registry is the single source of truth for:
 *   - SARIF `reportingDescriptors` (rules block)
 *   - Baseline fingerprinting
 *   - `--disable-rule`, `--min-severity` filtering
 *   - CWE / OWASP taxonomies surfaced in reports
 *
 * Rule IDs are stable contract — never renumber or rename an existing id. Add new ids
 * and deprecate old ones via the optional `deprecated` flag below.
 */
export interface RuleDefinition {
  id: string;
  title: string;
  category: IssueCategory;
  defaultSeverity: Severity;
  cwe: string[];
  owasp: string;
  description: string;
  recommendation: string;
  /**
   * Heuristic rules fire on weaker signals (regex/keyword-only) and are off by default.
   * They surface only with `--enable-heuristics`.
   */
  heuristic?: boolean;
  /**
   * Mark true to keep the rule in the catalog but exclude it from emit. Useful when a
   * detector has been retired but ids must remain reserved for baseline stability.
   */
  deprecated?: boolean;
}

const RULES: RuleDefinition[] = [
  // ── AUTHENTICATION ─────────────────────────────────────────────────────────
  {
    id: 'BCR-AUTH-001',
    title: 'Unverified Token Usage',
    category: 'AUTHENTICATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-287', 'CWE-345'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Token is accessed without prior verification or validation.',
    recommendation: 'Verify and validate the token before using it. Use middleware like jwt.verify().',
    heuristic: true,
  },
  {
    id: 'BCR-AUTH-002',
    title: 'Hardcoded Secret/Token',
    category: 'AUTHENTICATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-798', 'CWE-259'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Secret, password, or key appears to be hardcoded in the source.',
    recommendation: 'Move secrets to environment variables or a secure vault (e.g., .env, AWS Secrets Manager).',
  },
  {
    id: 'BCR-AUTH-003',
    title: 'Sensitive Function Without Auth Guard',
    category: 'AUTHENTICATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-306'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Route performs sensitive operations without authentication checks.',
    recommendation: 'Add authentication middleware or verified identity checks before executing sensitive route logic.',
  },
  {
    id: 'BCR-AUTH-004',
    title: 'Hardcoded Secret in Variable',
    category: 'AUTHENTICATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-798'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Variable contains a hardcoded secret or sensitive value.',
    recommendation: 'Use environment variables or secure configuration management instead.',
  },

  // ── JWT ────────────────────────────────────────────────────────────────────
  {
    id: 'BCR-JWT-001',
    title: 'JWT Signature Not Verified',
    category: 'AUTHENTICATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-345', 'CWE-347'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Token is decoded without verifying the signature. Attacker can forge arbitrary tokens.',
    recommendation: 'Always use jwt.verify() to validate the signature before trusting the token claims.',
  },
  {
    id: 'BCR-JWT-002',
    title: 'Algorithm Confusion Attack - None Algorithm Allowed',
    category: 'AUTHENTICATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-327', 'CWE-347'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'JWT verification allows the "none" algorithm. Attacker can create unsigned tokens that pass verification.',
    recommendation: 'Never allow the "none" algorithm. Explicitly specify allowed algorithms: { algorithms: ["HS256"] }',
  },
  {
    id: 'BCR-JWT-003',
    title: 'Missing Algorithm Specification',
    category: 'AUTHENTICATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-327'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'JWT verification does not explicitly specify allowed algorithms, making it vulnerable to algorithm substitution attacks.',
    recommendation: 'Explicitly specify allowed algorithms in verify options: { algorithms: ["HS256"] }',
    heuristic: true,
  },
  {
    id: 'BCR-JWT-004',
    title: 'Key Confusion Attack - Public Key with HMAC',
    category: 'AUTHENTICATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-327'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Algorithm is HS256 (HMAC) but using a public key as the secret. Attacker can forge tokens using the public key.',
    recommendation: 'Use symmetric algorithms (HS256) with a private secret, or asymmetric algorithms (RS256) with private/public keys. Never mix them.',
  },
  {
    id: 'BCR-JWT-005',
    title: 'Weak JWT Secret Key',
    category: 'AUTHENTICATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-326', 'CWE-521'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'JWT secret key is too short. Should be at least 32 characters (256 bits) for HMAC.',
    recommendation: 'Use a cryptographically random secret of at least 32 characters (256 bits). Use: crypto.randomBytes(32).toString("hex")',
  },
  {
    id: 'BCR-JWT-006',
    title: 'JWT Expiration Check Disabled',
    category: 'AUTHENTICATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-613'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Verification ignores token expiration time. Old/revoked tokens will be accepted indefinitely.',
    recommendation: 'Remove ignoreExpiration flag and validate exp claim. Set: { ignoreExpiration: false }',
  },
  {
    id: 'BCR-JWT-007',
    title: 'Cached JWT Without Expiration Validation',
    category: 'AUTHENTICATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-613'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Decoded JWT is cached without proper expiration validation. Revoked or expired tokens may still be accepted.',
    recommendation: 'Always verify JWT freshness. Implement token blacklist/revocation checks and never cache decoded tokens indefinitely.',
    heuristic: true,
  },
  {
    id: 'BCR-JWT-008',
    title: 'Missing Key ID (kid) Validation',
    category: 'AUTHENTICATION',
    defaultSeverity: 'MEDIUM',
    cwe: ['CWE-345'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'JWT key ID (kid) claim is not validated. Attacker could specify an arbitrary kid to confuse key selection logic.',
    recommendation: 'Always validate the kid claim and ensure it matches an expected key ID in your key store.',
    heuristic: true,
  },

  // ── VALIDATION / INJECTION ─────────────────────────────────────────────────
  {
    id: 'BCR-VAL-001',
    title: 'Unvalidated Input Reaches SQL Query Construction',
    category: 'VALIDATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-89'],
    owasp: 'A03:2021 - Injection',
    description: 'User-controlled input is interpolated into a raw SQL query.',
    recommendation: 'Use parameterized queries or ORM placeholders. Validate and constrain dynamic field names through a server-side allowlist.',
  },
  {
    id: 'BCR-VAL-002',
    title: 'Unvalidated Input Reaches Command Execution',
    category: 'VALIDATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-78', 'CWE-77'],
    owasp: 'A03:2021 - Injection',
    description: 'User-controlled input flows into an operating system command sink.',
    recommendation: 'Avoid shell invocation with request data. Use safe APIs with fixed arguments and strict allowlists.',
  },
  {
    id: 'BCR-VAL-003',
    title: 'Unvalidated Input Reaches Dynamic Code Execution',
    category: 'VALIDATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-94', 'CWE-95'],
    owasp: 'A03:2021 - Injection',
    description: 'User-controlled input reaches a dynamic code execution sink.',
    recommendation: 'Remove dynamic code execution for untrusted data. Parse structured input instead of evaluating it.',
  },
  {
    id: 'BCR-VAL-004',
    title: 'Unvalidated Input Reaches File-System Sink',
    category: 'VALIDATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-22', 'CWE-23'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'User-controlled input reaches a file-system API without path validation.',
    recommendation: 'Canonicalize paths, enforce directory allowlists, and reject user-controlled traversal sequences before file access.',
    deprecated: true,
  },
  {
    id: 'BCR-VAL-005',
    title: 'Unsafe JSON.parse with User Input',
    category: 'VALIDATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-502', 'CWE-1321'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'User input is directly passed to JSON.parse without sanitization.',
    recommendation: 'Validate JSON structure using a JSON schema validator. Use JSON.parse with a reviver function to filter out __proto__ and constructor properties.',
  },
  {
    id: 'BCR-VAL-006',
    title: 'Code Injection via eval() Deserialization',
    category: 'VALIDATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-95', 'CWE-502'],
    owasp: 'A03:2021 - Injection',
    description: 'User input is passed to eval() or Function constructor for deserialization.',
    recommendation: 'Never use eval() or Function constructor with untrusted input. Use JSON.parse for JSON data or safe serialization libraries.',
  },
  {
    id: 'BCR-VAL-007',
    title: 'Prototype Pollution Vulnerability',
    category: 'VALIDATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-1321'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'User input is assigned to __proto__ or constructor.prototype, allowing prototype pollution attacks.',
    recommendation: 'Use Object.preventExtensions() and Object.freeze() to lock prototypes. Validate input strictly and filter __proto__ and constructor properties.',
  },
  {
    id: 'BCR-VAL-008',
    title: 'Unsafe Object.assign with Untrusted Data',
    category: 'VALIDATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-915', 'CWE-1321'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'Object.assign is used with untrusted data as source, which can pollute the target object.',
    recommendation: 'Validate input structure before Object.assign. Use a whitelist of allowed properties or use Object.create(null) for target objects.',
    heuristic: true,
  },
  {
    id: 'BCR-VAL-009',
    title: 'Unsafe Object Spread with Untrusted Data',
    category: 'VALIDATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-915'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'Spread operator is used with untrusted data to merge into objects.',
    recommendation: 'Validate and filter input properties before spreading. Use a property whitelist to only spread allowed properties.',
    heuristic: true,
  },
  {
    id: 'BCR-VAL-010',
    title: 'Potential Gadget Chain Usage',
    category: 'VALIDATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-502'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'Code uses object methods that could be part of gadget chains with untrusted input.',
    recommendation: 'Avoid using untrusted data with methods that could be part of gadget chains.',
    heuristic: true,
  },

  // ── LOGGING ────────────────────────────────────────────────────────────────
  {
    id: 'BCR-LOG-001',
    title: 'Sensitive Data in Logs',
    category: 'LOGGING',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-532', 'CWE-200'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'Log statement contains sensitive data (passwords, tokens, API keys, credentials).',
    recommendation: 'Remove sensitive data from logs. Mask or redact passwords, tokens, and API keys.',
  },
  {
    id: 'BCR-LOG-002',
    title: 'Log Injection Risk',
    category: 'LOGGING',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-117'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'User input is directly interpolated into log messages.',
    recommendation: 'Log user input separately and use structured logging to prevent injection attacks.',
  },

  // ── MASS ASSIGNMENT ────────────────────────────────────────────────────────
  {
    id: 'BCR-MA-001',
    title: 'Direct Object.assign with User Input',
    category: 'MASS_ASSIGNMENT',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-915'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Object.assign is used with unvalidated user input, risking mass assignment attacks.',
    recommendation: 'Use explicit field assignment or whitelist allowed properties before assigning.',
  },
  {
    id: 'BCR-MA-002',
    title: 'Unvalidated Field Assignment',
    category: 'MASS_ASSIGNMENT',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-915'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Object property directly assigned from user input without validation.',
    recommendation: 'Validate field names and values before assignment. Use a whitelist approach.',
  },
  {
    id: 'BCR-MA-003',
    title: 'Missing Field Whitelisting',
    category: 'MASS_ASSIGNMENT',
    defaultSeverity: 'MEDIUM',
    cwe: ['CWE-915'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Function assigns object properties without field whitelisting.',
    recommendation: 'Implement field whitelisting to explicitly define which properties can be assigned.',
    heuristic: true,
  },
  {
    id: 'BCR-MA-004',
    title: 'Prototype Pollution Vulnerability',
    category: 'MASS_ASSIGNMENT',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-1321'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'Direct assignment to __proto__ or prototype can lead to prototype pollution.',
    recommendation: 'Never allow assignment to __proto__ or prototype properties. Use Object.create(null) or validate deeply.',
  },
  {
    id: 'BCR-MA-005',
    title: 'Constructor/Prototype Property Assignment',
    category: 'MASS_ASSIGNMENT',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-1321'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'Object contains constructor or prototype properties that can be exploited.',
    recommendation: 'Avoid assigning to constructor, prototype, or __proto__ properties.',
  },

  // ── ACCESS CONTROL ─────────────────────────────────────────────────────────
  {
    id: 'BCR-AC-001',
    title: 'Missing Authorization Check on Sensitive Endpoint',
    category: 'ACCESS_CONTROL',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-862', 'CWE-285'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'Route handles a sensitive action but no role, permission, or ownership guard is visible.',
    recommendation: 'Add authorization middleware or inline ownership/role checks before executing sensitive route logic.',
  },
  {
    id: 'BCR-AC-002',
    title: 'BOLA: Predictable ID Used Without Ownership Check',
    category: 'ACCESS_CONTROL',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-639', 'CWE-284'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'A user-supplied ID parameter is accessed directly without verifying that the current user owns this resource.',
    recommendation: 'Always verify that the authenticated user owns the resource before returning it.',
  },
  {
    id: 'BCR-AC-003',
    title: 'Missing Ownership Verification (Horizontal Escalation)',
    category: 'ACCESS_CONTROL',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-639'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'Database query retrieves a resource by ID without verifying the current user owns it.',
    recommendation: 'Add an additional condition to the query to verify user ownership.',
  },
  {
    id: 'BCR-AC-004',
    title: 'Potential Privilege Escalation (Vertical)',
    category: 'ACCESS_CONTROL',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-269'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'Function performs privileged operations without verifying user role.',
    recommendation: 'Add explicit role/permission checks at the beginning of the function.',
  },
  {
    id: 'BCR-AC-005',
    title: 'IDOR: Direct Object Reference Without Access Check',
    category: 'ACCESS_CONTROL',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-639'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'Object is accessed directly using user-supplied ID without verifying the user has access permission.',
    recommendation: 'After retrieving the object, verify that the current user is authorized to access it before returning or modifying it.',
  },

  // ── RATE LIMITING ──────────────────────────────────────────────────────────
  {
    id: 'BCR-RL-001',
    title: 'Missing Rate Limiting on Sensitive Endpoint',
    category: 'RATE_LIMITING',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-770', 'CWE-307'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'The endpoint does not have rate limiting middleware configured.',
    recommendation: 'Add rate limiting middleware (e.g. express-rate-limit) with strict limits for sensitive endpoints.',
    heuristic: true,
  },
  {
    id: 'BCR-RL-002',
    title: 'Rate Limit Bypass via Header Manipulation',
    category: 'RATE_LIMITING',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-290', 'CWE-770'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'The rate limit key generator relies on request IP data without visible trusted-proxy validation.',
    recommendation: 'Only trust proxy headers from your own infrastructure and derive the client IP through a trusted helper.',
  },
  {
    id: 'BCR-RL-003',
    title: 'Weak Rate Limiting on Sensitive Endpoint',
    category: 'RATE_LIMITING',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-770'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Rate limit per minute is too high for a sensitive endpoint.',
    recommendation: 'Reduce rate limits on sensitive endpoints to 5-10 requests per minute.',
  },
  {
    id: 'BCR-RL-004',
    title: 'Distributed Rate Limit Bypass via Load Balancer',
    category: 'RATE_LIMITING',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-770'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Rate limiting uses in-memory storage, which is not shared across multiple server instances.',
    recommendation: 'Use a distributed cache backend for rate limiting (e.g. Redis).',
  },

  // ── BUSINESS LOGIC ─────────────────────────────────────────────────────────
  {
    id: 'BCR-BL-001',
    title: 'Business Logic - Race Condition',
    category: 'BUSINESS_LOGIC',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-362', 'CWE-367'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Concurrent operation without locking or transaction may cause race condition.',
    recommendation: 'Wrap state-changing reads + writes in a transaction or distributed lock.',
    heuristic: true,
  },
  {
    id: 'BCR-BL-002',
    title: 'Business Logic - Idempotency',
    category: 'BUSINESS_LOGIC',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-841'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Operation may be replayed without idempotency protection.',
    recommendation: 'Require an idempotency key and store it server-side.',
    heuristic: true,
  },
  {
    id: 'BCR-BL-003',
    title: 'Business Logic - Time-of-Check / Time-of-Use',
    category: 'BUSINESS_LOGIC',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-367'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'State checked before use may change between check and use.',
    recommendation: 'Combine check and update inside an atomic transaction.',
    heuristic: true,
  },
  {
    id: 'BCR-BL-004',
    title: 'Business Logic - Client-Controlled Price',
    category: 'BUSINESS_LOGIC',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-602'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Price or amount is taken from client input without server-side authority.',
    recommendation: 'Always derive prices server-side from a trusted source.',
    heuristic: true,
  },
  {
    id: 'BCR-BL-005',
    title: 'Business Logic - Inventory Over-Selling',
    category: 'BUSINESS_LOGIC',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-362'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Inventory decrement is not atomic, enabling over-selling.',
    recommendation: 'Decrement inventory atomically within the order transaction.',
    heuristic: true,
  },

  // ── API KEY EXPOSURE ───────────────────────────────────────────────────────
  {
    id: 'BCR-KEY-001',
    title: 'Hardcoded Service API Key',
    category: 'API_KEY_EXPOSURE',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-798'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'API key matching a known service format is hardcoded in source.',
    recommendation: 'Move the key to environment variables or a secrets manager.',
  },
  {
    id: 'BCR-KEY-002',
    title: 'Hardcoded Key in Configuration File',
    category: 'API_KEY_EXPOSURE',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-798'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'API key or secret is hardcoded in a configuration file.',
    recommendation: 'Use environment variables or a secrets manager.',
    heuristic: true,
  },
  {
    id: 'BCR-KEY-003',
    title: 'Hardcoded Key in Function Default Parameter',
    category: 'API_KEY_EXPOSURE',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-798'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Function parameter has a hardcoded API key or secret as default value.',
    recommendation: 'Remove hardcoded defaults. Use dependency injection or environment variables instead.',
  },
  {
    id: 'BCR-KEY-004',
    title: 'API Key in Comment',
    category: 'API_KEY_EXPOSURE',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-798', 'CWE-540'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'API key is exposed in a code comment.',
    recommendation: 'Remove all credentials from comments. Use environment variables or secrets managers.',
  },
  {
    id: 'BCR-KEY-005',
    title: 'API Key in Logs',
    category: 'API_KEY_EXPOSURE',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-532', 'CWE-798'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'API key is being logged.',
    recommendation: 'Remove credentials from log output. Implement logging filters or use a logging library that strips sensitive data.',
  },
  {
    id: 'BCR-KEY-006',
    title: 'API Key in Error Message',
    category: 'API_KEY_EXPOSURE',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-209'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'API key exposed in an error message.',
    recommendation: 'Remove sensitive data from error messages. Log full errors internally but show sanitized messages to users.',
  },
  {
    id: 'BCR-KEY-007',
    title: 'Database Credentials in Connection String',
    category: 'API_KEY_EXPOSURE',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-798'],
    owasp: 'A07:2021 - Identification and Authentication Failures',
    description: 'Database connection string contains hardcoded username and password.',
    recommendation: 'Use environment variables for database credentials.',
  },

  // ── CRYPTO WEAKNESS ────────────────────────────────────────────────────────
  {
    id: 'BCR-CRYPTO-001',
    title: 'Weak Hashing of Password/Secret',
    category: 'CRYPTO_WEAKNESS',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-327', 'CWE-916'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'MD5/SHA1 used to hash passwords or secrets — these algorithms are broken for this purpose.',
    recommendation: 'Use bcrypt, scrypt, or Argon2 for passwords.',
    heuristic: true,
  },
  {
    id: 'BCR-CRYPTO-002',
    title: 'Predictable token with Math.random()',
    category: 'CRYPTO_WEAKNESS',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-338', 'CWE-330'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'Math.random() is not cryptographically secure for token generation.',
    recommendation: 'Use crypto.randomBytes() or crypto.randomUUID().',
  },
  {
    id: 'BCR-CRYPTO-003',
    title: 'Hardcoded cryptographic key',
    category: 'CRYPTO_WEAKNESS',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-321', 'CWE-798'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'Cryptographic key is hardcoded in source.',
    recommendation: 'Use environment variables or a secrets manager.',
  },

  // ── DATA EXPOSURE ──────────────────────────────────────────────────────────
  {
    id: 'BCR-DE-001',
    title: 'Unfiltered sensitive data in API response',
    category: 'DATA_EXPOSURE',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-200', 'CWE-359'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'Response object contains sensitive fields that should be excluded.',
    recommendation: 'Filter sensitive fields before returning. Use a DTO/serializer.',
    heuristic: true,
  },
  {
    id: 'BCR-DE-002',
    title: 'Sensitive field exposed in response',
    category: 'DATA_EXPOSURE',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-200'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'A sensitive field is explicitly written to an API response.',
    recommendation: 'Exclude the field from response shapes.',
  },

  // ── CACHE POISONING ────────────────────────────────────────────────────────
  {
    id: 'BCR-CACHE-001',
    title: 'Exploitable Cache Poisoning via User-Controlled Cache Key',
    category: 'CACHE_POISONING',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-444', 'CWE-349'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Cache key is derived from attacker-controlled request data without normalization.',
    recommendation: 'Use trusted server-side identifiers for cache keys and normalize any externally influenced dimensions before cache writes.',
  },
  {
    id: 'BCR-CACHE-002',
    title: 'Exploitable Cache Poisoning via HTTP Header Keying',
    category: 'CACHE_POISONING',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-444', 'CWE-349'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'Cache keying uses attacker-controlled HTTP headers (Host, X-Forwarded-For).',
    recommendation: 'Use trusted server-side identifiers for cache keys. Normalize externally influenced dimensions before cache writes.',
  },

  // ── MESSAGE QUEUE / EVENT STREAM (HEURISTIC) ───────────────────────────────
  {
    id: 'BCR-MQ-001',
    title: 'Queue Consumer Deserialization Without Validation',
    category: 'MESSAGE_QUEUE',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-502'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'Queue consumer deserializes message payload without schema validation.',
    recommendation: 'Validate every consumed message against an explicit schema before processing.',
  },
  {
    id: 'BCR-MQ-002',
    title: 'Unsigned Queue Publish',
    category: 'MESSAGE_QUEUE',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-345'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'Queue publish does not include an integrity signature.',
    recommendation: 'Sign queue payloads and verify on consume.',
    heuristic: true,
  },
  {
    id: 'BCR-MQ-003',
    title: 'Integrity Not Verified Before Ack',
    category: 'MESSAGE_QUEUE',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-354'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: 'Message is acknowledged before integrity verification.',
    recommendation: 'Verify integrity before ack.',
    heuristic: true,
  },
  {
    id: 'BCR-EVT-001',
    title: 'Event Handler Injection',
    category: 'EVENT_STREAM',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-94'],
    owasp: 'A03:2021 - Injection',
    description: 'Event handler name is derived from untrusted input.',
    recommendation: 'Allowlist event names server-side.',
  },
  {
    id: 'BCR-EVT-002',
    title: 'Event Name Enables Handler Abuse',
    category: 'EVENT_STREAM',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-94'],
    owasp: 'A03:2021 - Injection',
    description: 'Event subscription accepts arbitrary handler names.',
    recommendation: 'Restrict subscription to a server-side allowlist.',
    heuristic: true,
  },
  {
    id: 'BCR-EVT-003',
    title: 'Missing Tenant Scoping in Event Subscription',
    category: 'EVENT_STREAM',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-639'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'Event subscription does not scope by tenant/owner.',
    recommendation: 'Scope subscriptions to the current tenant.',
    heuristic: true,
  },

  // ── SSRF ───────────────────────────────────────────────────────────────────
  {
    id: 'BCR-SSRF-001',
    title: 'SSRF: Outbound Request Built From User Input',
    category: 'SSRF',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-918'],
    owasp: 'A10:2021 - Server-Side Request Forgery (SSRF)',
    description: 'An outbound HTTP request (fetch/axios/got/http.get/request) targets a URL built from user-controlled input without an allowlist.',
    recommendation: 'Constrain outbound URLs through a server-side allowlist of hosts and schemes. Reject non-HTTPS, non-public destinations, and resolve DNS in advance to defend against DNS rebinding.',
  },

  // ── OPEN REDIRECT ──────────────────────────────────────────────────────────
  {
    id: 'BCR-REDIRECT-001',
    title: 'Open Redirect: res.redirect() Receives User Input',
    category: 'OPEN_REDIRECT',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-601'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'An HTTP redirect target is taken from request data without validation, enabling open-redirect / phishing chains.',
    recommendation: 'Validate the redirect URL against a server-side allowlist or reject any absolute URL and only allow relative paths.',
  },

  // ── PATH TRAVERSAL ─────────────────────────────────────────────────────────
  {
    id: 'BCR-PT-001',
    title: 'Path Traversal: File-System Sink Reads User-Controlled Path',
    category: 'PATH_TRAVERSAL',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-22', 'CWE-23'],
    owasp: 'A01:2021 - Broken Access Control',
    description: 'A file-system call (readFile/writeFile/createReadStream) receives a path derived from user input without canonicalization or directory allowlist.',
    recommendation: 'Resolve the path against a fixed base directory and reject any result outside it. Reject path components containing `..` and absolute paths.',
  },

  // ── TAGGED TEMPLATE SQL ────────────────────────────────────────────────────
  {
    id: 'BCR-VAL-011',
    title: 'SQL Injection via Tagged-Template With Tainted Substitution',
    category: 'VALIDATION',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-89'],
    owasp: 'A03:2021 - Injection',
    description: 'A tagged template literal (e.g. sql`SELECT * FROM x WHERE id=${...}`) embeds user-controlled data as a substitution.',
    recommendation: 'Use parameterized placeholders supported by your query library, or constrain dynamic field names through a server-side allowlist.',
  },

  // ── MISCONFIGURATION ───────────────────────────────────────────────────────
  {
    id: 'BCR-MISC-001',
    title: 'Permissive CORS Configuration',
    category: 'MISCONFIGURATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-942', 'CWE-346'],
    owasp: 'A05:2021 - Security Misconfiguration',
    description: 'CORS middleware allows any origin (`*` or `true`) which enables cross-origin reads of authenticated responses.',
    recommendation: 'Configure CORS with an explicit allowlist of origins. Never use `origin: "*"` on routes that require credentials.',
  },
  {
    id: 'BCR-MISC-002',
    title: 'Body Parser Without Size Limit',
    category: 'MISCONFIGURATION',
    defaultSeverity: 'MEDIUM',
    cwe: ['CWE-770'],
    owasp: 'A05:2021 - Security Misconfiguration',
    description: 'express.json() / express.urlencoded() / body-parser.json() is configured without an explicit `limit` field. The default 100kb is high enough for DoS via large payloads on many endpoints.',
    recommendation: 'Set an explicit `limit` (e.g. `{ limit: "100kb" }`) per parser based on actual payload requirements.',
    heuristic: true,
  },
  {
    id: 'BCR-MISC-003',
    title: 'Helmet Configured Without Options',
    category: 'MISCONFIGURATION',
    defaultSeverity: 'LOW',
    cwe: ['CWE-693'],
    owasp: 'A05:2021 - Security Misconfiguration',
    description: 'helmet() is registered with no options, accepting all defaults. Modern applications should explicitly opt into a CSP and HSTS configuration that matches their domain.',
    recommendation: 'Pass an explicit options object: `helmet({ contentSecurityPolicy: {...}, hsts: { maxAge: ... } })`.',
    heuristic: true,
  },
  {
    id: 'BCR-MISC-004',
    title: 'Weak bcrypt Cost Factor',
    category: 'MISCONFIGURATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-916', 'CWE-326'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'bcrypt is called with a cost factor under 10. Modern hardware brute-forces low-cost bcrypt hashes quickly.',
    recommendation: 'Use a cost factor of at least 10 (current OWASP guidance: 12).',
  },
  {
    id: 'BCR-CRYPTO-005',
    title: 'Deprecated crypto.createCipher (IV-less)',
    category: 'CRYPTO_WEAKNESS',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-327', 'CWE-329'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'crypto.createCipher / createDecipher derive the IV from the key and are deprecated. They produce identical ciphertext for identical plaintexts and are vulnerable to chosen-plaintext attacks.',
    recommendation: 'Use createCipheriv / createDecipheriv with a unique random IV per encryption (crypto.randomBytes(16)).',
  },
  {
    id: 'BCR-MA-006',
    title: 'Mass Assignment via Service Call With req.body',
    category: 'MASS_ASSIGNMENT',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-915'],
    owasp: 'A04:2021 - Insecure Design',
    description: 'A `create*`/`update*`/`register*`/`save*` call receives `req.body` directly, with no visible schema validation in the enclosing scope. The ORM model picks up every attacker-supplied field including role / isAdmin / verified.',
    recommendation: 'Validate request payloads against an explicit schema (zod, joi, class-validator) before passing to service / ORM calls. Or use a whitelist (`pick`) extracting only allowed fields.',
  },
  {
    id: 'BCR-VAL-012',
    title: 'Insecure Deserialization From Base64',
    category: 'VALIDATION',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-502'],
    owasp: 'A08:2021 - Software and Data Integrity Failures',
    description: '`Buffer.from(x, "base64").toString()` decodes attacker-controlled base64 and chains it into JSON.parse or credential splitting. Common in poorly-implemented Basic auth and webhook signature verification.',
    recommendation: 'Validate the decoded payload against a strict schema before parsing. For Basic auth, use a hardened library like `basic-auth`. For webhook signatures, verify HMAC before decoding.',
  },

  // ── ID FROM WEAK RANDOMNESS ────────────────────────────────────────────────
  {
    id: 'BCR-CRYPTO-004',
    title: 'Identifier or Session Token Generated With Math.random()',
    category: 'CRYPTO_WEAKNESS',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-338', 'CWE-330'],
    owasp: 'A02:2021 - Cryptographic Failures',
    description: 'Math.random() output is used as an identifier, session id, nonce, or reset code. Math.random is not cryptographically secure and is predictable.',
    recommendation: 'Use crypto.randomBytes() / crypto.randomUUID() for any identifier carrying security weight.',
  },

  // ╔═══════════════════════════════════════════════════════════════════════╗
  // ║ LOG REVIEW RULES (mode=logs). Scoped to PCI-DSS / UAE PDPL / GDPR.    ║
  // ╚═══════════════════════════════════════════════════════════════════════╝

  // ── PCI: cardholder data in logs ──────────────────────────────────────────
  {
    id: 'LOG-PCI-001',
    title: 'Primary Account Number (PAN) in log message',
    category: 'LOG_PCI',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-532', 'CWE-359'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A 13-19 digit string that passes the Luhn checksum appears in a log message. PCI-DSS Req 3.4 requires PAN to be unreadable in storage; logs count as storage.',
    recommendation: 'Mask or truncate the PAN at the application layer before logging (first 6 + last 4 max per PCI-DSS 3.3). Audit the source code path that emitted this log; rotate any cards exposed in retained log volumes.',
  },
  {
    id: 'LOG-PCI-002',
    title: 'Card Verification Value (CVV/CVC) in log message',
    category: 'LOG_PCI',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-532'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A CVV/CVC pattern appears in a log line. PCI-DSS Req 3.2 prohibits storing sensitive authentication data (including CVV) post-authorization, EVEN encrypted. Logs are storage.',
    recommendation: 'Strip CVV at the request boundary. Audit code paths emitting this log; rotate the affected accounts.',
  },
  {
    id: 'LOG-PCI-003',
    title: 'Magnetic Stripe Track Data in log message',
    category: 'LOG_PCI',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-532'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'Track 1 or Track 2 data signature detected in a log line. PCI-DSS prohibits storage of full track data under any condition.',
    recommendation: 'Identify and remove the code path emitting track data. Treat the affected log volume as a breach; notify the acquirer per PCI-DSS Req 12.10.',
  },

  // ── PII: identifiers in logs (UAE-specific + global) ──────────────────────
  {
    id: 'LOG-PII-001',
    title: 'UAE Emirates ID in log message',
    category: 'LOG_PII',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-359'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A 15-digit Emirates ID pattern (784-YYYY-XXXXXXX-X) appears in a log line. UAE PDPL Article 24 and CBUAE Consumer Protection Standards classify this as sensitive personal data.',
    recommendation: 'Hash or pseudonymise the Emirates ID at the application layer. Restrict access to historical log volumes that may still contain the ID.',
  },
  {
    id: 'LOG-PII-002',
    title: 'IBAN in log message',
    category: 'LOG_PII',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-359'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A string passing IBAN format + mod-97 checksum appears in a log line. UAE IBANs (AE) and other ISO 13616 IBANs are personal financial identifiers.',
    recommendation: 'Mask all but the last 4 digits of any IBAN before logging. Audit retention of historical log volumes.',
  },
  {
    id: 'LOG-PII-003',
    title: 'Email address in log message (potentially identifying customer)',
    category: 'LOG_PII',
    defaultSeverity: 'MEDIUM',
    cwe: ['CWE-359'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A syntactically valid email address appears in a log line. May be acceptable for operational metadata; reviewer should confirm whether the address belongs to a customer.',
    recommendation: 'Hash or domain-mask customer emails. Operational/internal addresses (e.g., service accounts) are typically acceptable.',
    heuristic: true,
  },
  {
    id: 'LOG-PII-004',
    title: 'UAE phone number in log message',
    category: 'LOG_PII',
    defaultSeverity: 'MEDIUM',
    cwe: ['CWE-359'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A UAE-formatted phone number (+971-prefix or 05X local) appears in a log line.',
    recommendation: 'Mask the local portion of customer phone numbers. Keep only the country prefix and last 2 digits for diagnostic purposes.',
  },
  {
    id: 'LOG-PII-005',
    title: 'Passport number pattern in log message',
    category: 'LOG_PII',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-359'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A pattern that resembles an international passport number appears in a log line.',
    recommendation: 'Never log passport numbers in plaintext. Hash or store separately under stricter access controls.',
    heuristic: true,
  },

  // ── Secrets in logs ───────────────────────────────────────────────────────
  {
    id: 'LOG-SEC-001',
    title: 'Plaintext password in log message',
    category: 'LOG_SECRET',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-532', 'CWE-256'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A `password=` / `pwd=` / `passwd=` key-value pattern with a non-trivial value appears in a log line.',
    recommendation: 'Strip password fields at the request boundary before any logger touches them. Rotate any credentials that appear in retained log volumes.',
  },
  {
    id: 'LOG-SEC-002',
    title: 'Bearer token or JWT in log message',
    category: 'LOG_SECRET',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-532'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A Bearer authorization header or JWT (3-part base64url string) appears in a log line. Logged tokens are session-equivalent credentials.',
    recommendation: 'Redact Authorization headers in the logging middleware. Revoke any tokens that appear in retained log volumes.',
  },
  {
    id: 'LOG-SEC-003',
    title: 'Service API key in log message',
    category: 'LOG_SECRET',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-532', 'CWE-798'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A key matching a known service format (Stripe, AWS, GitHub, SendGrid, Firebase, Twilio) appears in a log line.',
    recommendation: 'Rotate the exposed key immediately. Identify the code path that logged the key and add a redaction filter.',
  },
  {
    id: 'LOG-SEC-004',
    title: 'Private key block in log message',
    category: 'LOG_SECRET',
    defaultSeverity: 'CRITICAL',
    cwe: ['CWE-532', 'CWE-798'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A PEM private-key block (`-----BEGIN ... PRIVATE KEY-----`) appears in a log line.',
    recommendation: 'Rotate the exposed key immediately. Investigate the path that emitted it.',
  },

  // ── Ops: log-integrity / monitoring failures ──────────────────────────────
  {
    id: 'LOG-OPS-001',
    title: 'Database connection error revealing credentials in log',
    category: 'LOG_OPS',
    defaultSeverity: 'HIGH',
    cwe: ['CWE-209', 'CWE-532'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A database driver error message that includes a connection string with username:password embedded.',
    recommendation: 'Configure the DB client to strip credentials from connection-failure logs. Rotate the exposed credential.',
  },
  {
    id: 'LOG-OPS-002',
    title: 'Stack trace containing sensitive file path',
    category: 'LOG_OPS',
    defaultSeverity: 'LOW',
    cwe: ['CWE-209'],
    owasp: 'A09:2021 - Security Logging and Monitoring Failures',
    description: 'A stack trace exposes absolute filesystem paths including possibly-sensitive directory names (`secrets`, `keys`, `vault`).',
    recommendation: 'Use a structured logger that strips file paths or maps them to safe identifiers.',
    heuristic: true,
  },
];

const BY_ID = new Map<string, RuleDefinition>(RULES.map((rule) => [rule.id, rule]));

export function getRule(id: string): RuleDefinition | undefined {
  return BY_ID.get(id);
}

export function listRules(): RuleDefinition[] {
  return [...RULES];
}

export function isHeuristic(ruleId: string): boolean {
  return BY_ID.get(ruleId)?.heuristic === true;
}

const SEVERITY_RANK: Record<Severity, number> = {
  CRITICAL: 4,
  HIGH: 3,
  MEDIUM: 2,
  LOW: 1,
  INFO: 0,
};

export function severityAtLeast(value: Severity, threshold: Severity): boolean {
  return SEVERITY_RANK[value] >= SEVERITY_RANK[threshold];
}

export function severityRank(value: Severity): number {
  return SEVERITY_RANK[value];
}
